### PR TITLE
Implement benchmark in dart

### PR DESCRIPTION
**Pull request by Hari-07**
Dart implementation of loop and recursive fibonacci

### CODE REVIEW

**Comment by bddicken** [comment]
Thanks! Mind resolving the conflicts here?

**Comment by bddicken** [comment]
So that I can get this in ASAP, I'm gonna add this in with a separate commit. Hope you don't mind.

**Comment by bddicken** [comment]
Added in via commit 5d7ee9f1c633342e5b46495f38d1f131a9b50274

**Comment by Hari-07** [comment]
Thank you for fixing it, sorry I missed your comment about the conflicts. Must not have noticed, or might have happened after I created the PR

**Comment by Hari-07** [comment]
Not really sure what you were trying to do, but looking at the commit added in the conflicted files. You should have commited that to this branch and merged. Now your main has dart in the scripts but not the actual code itself.

**Comment by bddicken** [comment]
Thanks for pointing this out. I had them locally but had not added and pushed here.Should be on github now.

**Comment by PEZ** [comment]
@Hari-07 , we have moved over to in-process benchmark running. It would be wonderful if you wanted to help with porting the Dart implementations.

* #371

**Comment by Hari-07** [comment]
Yeah sure, will do it over the weekend

**Pull request closed without merging**
