### PR TITLE
add rust implementation for loop benchmark

### PR DESCRIPTION
**Pull request by saleem-mirza**
The code in rust is optimized using rayon https://docs.rs/rayon/latest/rayon/

Code implementation will take full advantage of modern multicore cpus. On my test machine, execution output is as below but your milage may vary.

```
time ./target/release/rust 100
4952670

real	0m0.076s
user	0m0.994s
sys	0m0.018s
```

Just for reference, C implementation's output

```
time ./cmain 100
4956807

real	0m0.741s
user	0m0.729s
sys	0m0.011s
```

### CODE REVIEW

**Comment by bddicken** [comment]
Interesting! I'm not a rust-ite, but it does look like you're introducing "extra" logic here to handle parallelism. Technically, we could do that in all of the other languages too and see a big performance boost, but have not (at least as of now). I think it would be better to either all be single-thread or all be parallel.

**Comment by arpadav** [comment]
spot on @bddicken 

the `rayon` crate performs a divide-and-conquer approach to parallelism. it would be nice if there is a different benchmark(s) for parallelism, since I agree that the `loops` benchmark was intentionally meant to be naively single-threaded

**Comment by bddicken** [comment]
Ok cool. Well, I think we should keep the `loops` directory non-parallel. If you'd like to add a `parallel` directory as a new benchmark you're welcome to, but I'm not sure who else is interested in getting all the other languages up to speed.

**Comment by saleem-mirza** [comment]
agreed, I didn't paid much attention. However, here is parallelized version of C code using openmp :)  enjoy

```
#include "stdio.h"
#include "stdlib.h"
#include "stdint.h"
#include "omp.h"

int main (int argc, char** argv) {
  int u = atoi(argv[1]);               // Get an input number from the command line
  int r = rand() % 10000;              // Get a random integer 0 <= r < 10k
  int32_t a[10000] = {0};              // Array of 10k elements initialized to 0
  
  #pragma omp parallel for
  {
    for (int i = 0; i < 10000; i++) {    // 10k outer loop iterations
      for (int j = 0; j < 100000; j++) { // 100k inner loop iterations, per outer loop iteration
        a[i] = a[i] + j%u;               // Simple sum
      }
      a[i] += r;                         // Add a random value to each element in array
    }
  }
  printf("%d\n", a[r]);                  // Print out a single element from the array
}

```

**Comment by saleem-mirza** [comment]
closing PR, since it is no more relevant

**Pull request closed without merging**
