### PR TITLE
 Add helloworld, loops and fibonacci in Emacs Lisp

### PR DESCRIPTION
**Pull request by a13**
I have:

* [x] Read the project [README](../README.md), including the [benchmark descriptions](../README.md#available-benchmarks)

## Description of changes
Added benchmarks in Emacs Lisp (somebody was going to do it anyway) :)

Not sure if I need to add anything Emacs related in Brewfile though.

Thanks

### CODE REVIEW

**Comment by PEZ** [comment]
Very cool! I would like to compile the native version. But get complaints about Emacs not being compiled for native. If you have some tips how to fix this on a Mac for a total Emacs noob, I would be super happy! 😄

**Comment by a13** [comment]
@PEZ 
Not sure if this is the best way, but this is what most Mac people use (I believe, since I don't have one, sorry)
```shell
brew tap d12frosted/emacs-plus
brew install emacs-plus@30 --with-native-comp
```

**Comment by PEZ** [comment]
Thanks! It took a lot of time, but works.

Another thing that took a lot of time, before I installed the native Emacs, was to run the benchmarks for the byte code versions. 😄  

I have a small project where I visualize the results for the languages where I have a toolchain and patience to wait. Here's a permalink for the first and only appearance of Emacs Lisp Bytecode:

* https://pez.github.io/languages-visualizations/v2024.12.30/

Even slower than Python! Haha.

The native compilation is much faster and I will publish the visualizations including that very soon, and probably will let it stay on the charts.

**Comment by PEZ** [comment]
Now with Emacs Lisp Native: https://pez.github.io/languages-visualizations/

**Comment by PEZ** [comment]
@a13 , please consider contributing a port of this to the new runner:

* #371 

I just added Racket. Would be cool to get all them Lisps in. 😄

**Pull request merged**
