### PR TITLE
levenshtein: add Pascal implementation

### PR DESCRIPTION
**Pull request by stalecu**

### CODE REVIEW

**Comment by PEZ** [comment]
Thanks for contributing! ❤️ 

Can you provide the result of running the latest run.sh with this implementation?

**Comment by stalecu** [comment]
> Thanks for contributing! ❤️
> 
> Can you provide the result of running the latest run.sh with this implementation?

```
Checking Free Pascal
Check passed
Benchmarking Free Pascal
Benchmark 1: ./fpc/code aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ...
  Time (mean ± σ):      34.7 ms ±   0.0 ms    [User: 34.0 ms, System: 0.3 ms]
  Range (min … max):    34.6 ms …  34.7 ms    3 runs
```
This is on an i5-8350U. For reference, here's C and C++:

```
Checking C
Check passed
Benchmarking C
Benchmark 1: ./c/code aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ...
  Time (mean ± σ):      13.3 ms ±   0.5 ms    [User: 12.7 ms, System: 0.3 ms]
  Range (min … max):    12.8 ms …  13.7 ms    3 runs

...

Checking CPP
Check passed
Benchmarking CPP
Benchmark 1: ./cpp/code aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ...
  Time (mean ± σ):      17.2 ms ±   0.7 ms    [User: 15.9 ms, System: 1.0 ms]
  Range (min … max):    16.4 ms …  17.9 ms    3 runs
```

**Comment by PEZ** [comment]
Awesome.

**Comment by basilevs** [comment]
@PEZ on your animation, Pascal is twice as quick as C. What's going on?

**Comment by PEZ** [comment]
I don't know what's going on. Would be great if others tried to reproduce and investigate.

**Comment by PEZ** [comment]
https://github.com/bddicken/languages/issues/347

**Pull request merged**
