### PR TITLE
Enable PHP's JIT

### PR DESCRIPTION
**Pull request by goetas**
As of PHP 8, JIT is available (many of the languages in the benchmark have JIT enabled by default)

With Jit enabled, on my Mac M3 php runs in 2.4s (previously was 9.6s).

### CODE REVIEW

**Comment by goetas** [comment]
@lcobucci  I have tried it, and surprisingly, it performs worse. it takes ~11s. By reading the docs, it says that splfixedarray takes less memory but says nothing about performance .

https://www.php.net/manual/en/class.splfixedarray.php
> The advantage is that it uses less memory than a standard array.

**Comment by lcobucci** [comment]
Interesting...

**Comment by chuoke** [comment]
On my old laptop, using this command is slower than without it.

**Comment by goetas** [comment]
@ilnytskyi my numbers were on php 8.4.1

**Comment by goetas** [comment]
@chuoke  which php version do you have?

**Comment by bddicken** [comment]
I have `PHP 8.3.13` on an M3 MBP, and for me, this does not seem to make a noticeable positive improvement for PHP. Am I doing something wrong?

**Comment by bddicken** [comment]
I'll just include both a jit and non-jit option for PHP

**Comment by goetas** [comment]
created https://github.com/bddicken/languages/pull/137

**Comment by chuoke** [comment]
> @chuoke which php version do you have?

 v8.3.14.

BTW, v8.4.1 is the slowest of all versions currently on my laptop.

**Pull request merged**
