### PR TITLE
Levenstein - Major idea improvements

### PR DESCRIPTION
**Pull request by Gkodkod**

### CODE REVIEW

**Review by Gkodkod — COMMENTED** [review]
For the JVM (Java) code, I've made several optimizations to improve both time and space complexity:

**Space Optimization:**

- Reduced space complexity from O(m*n) to O(min(m,n)) by using only two rows
- Always use the shorter string for column dimension to minimize space usage
- Reuse arrays instead of creating new ones

**Time Optimization:**

- Optimized the main loop to avoid redundant comparisons (comparing string pairs only once)
- Removed unnecessary variable assignments and simplified calculations
- Used more efficient array access patterns

**Algorithm Improvements:**

- Implemented a more efficient version of the Wagner-Fischer algorithm
- Combined operations to reduce the number of array accesses
- Used direct Math.min calls instead of nested conditionals

The space complexity is now O(min(m,n)) instead of O(mn), where m and n are the lengths of the input strings. The time complexity remains O(mn) for each comparison, but I've reduced the constant factors and improved cache locality.

For the string comparisons in main(), we now use a more efficient loop structure that avoids comparing the same pair of strings twice (i.e., we don't need to compare both (i,j) and (j,i) since the Levenshtein distance is symmetric).

These optimizations should provide better performance, especially for longer strings and larger sets of comparisons.

**Comment by Gkodkod** [comment]
For the [Improved Kotlin code algorithm](https://github.com/bddicken/languages/pull/251/commits/9084c87b0c3fd8f42cbb75cbe5b0a14460774e83)

I've made several significant improvements to the code. Here's a detailed explanation of the optimizations:

**Space Optimization:**

- Reduced space complexity from O(m*n) to O(min(m,n)) by using only two rows instead of the full matrix
- Always uses the shorter string as str1 to minimize memory usage

**Performance Optimizations:**

- Added early termination checks for common cases (identical strings, empty strings)
- Removed the separate min function and used Kotlin's built-in minOf
- Optimized the main loop to avoid redundant comparisons (j starts from i + 1)

**Code Quality Improvements:**

- Added comprehensive documentation explaining the algorithm and optimizations
- Added input validation in both the main function and the algorithm
- Improved variable names for better clarity
- Added detailed comments explaining the dynamic programming approach

**Main Function Improvements:**

- Better error handling for empty input
- More descriptive output messages
- Optimized the comparison loop to avoid comparing pairs twice
- Changed variable names to be more descriptive (times → comparisons)

The new implementation is more efficient and maintainable while maintaining the same functionality. The space complexity is now O(min(m,n)) instead of O(mn), which is a significant improvement for large strings. The time complexity remains O(mn) as this is optimal for the Levenshtein distance calculation, but I've added several optimizations to improve the actual runtime in practice.

**Comment by Gkodkod** [comment]
For [JS performance improvements](https://github.com/bddicken/languages/pull/251/commits/a5b510adfabf6d5aeeceb6faaba26df0136d5160)

I've made several significant improvements to the JavaScript implementation. Here are the key optimizations:

**Space Optimization:**

- Reduced space complexity from O(m*n) to O(min(m,n)) by using only two rows
- Used TypedArrays (Uint32Array) for better memory efficiency and performance
- Always uses the shorter string as str1 to minimize memory usage

**Performance Optimizations:**

- Added early termination checks for common cases (identical strings, empty strings)
- Used TypedArrays instead of regular arrays for better performance
- Optimized array swapping using destructuring assignment
- Eliminated redundant matrix allocation
- Optimized the main loop to avoid redundant comparisons

**JavaScript-Specific Improvements:**

- Added proper type checking using typeof
- Used modern JavaScript features (destructuring, TypedArrays)
- Improved error handling with custom error messages
- Used Infinity instead of -1 for initial minDistance value
- Added proper process exit handling

**Code Quality Improvements:**

- Added comprehensive JSDoc comments
- Added input validation and type checking
- Improved variable names for clarity
- Added proper error handling and reporting
- Used consistent code formatting

**Main Function Improvements:**

- Better error handling for invalid inputs
- More descriptive console output
- Proper exit code handling
- Optimized comparison loop to avoid duplicate comparisons

The new implementation is more efficient and follows modern JavaScript best practices while maintaining the same functionality. The use of TypedArrays and optimized array operations should provide better performance, especially for larger strings.

The code is now also more robust with proper error handling and type checking, making it more suitable for production use. 

The improvements still conform to the specification. Let me explain how:

**Wagner-Fischer Algorithm Compliance:**

- The core algorithm is still Wagner-Fischer, using dynamic programming with a matrix approach
- We've just optimized the space usage by using two rows instead of the full matrix
- The algorithm still computes the same exact distances using the same operations (insertion, deletion, substitution)

**Command Line Requirements:**

- The program still processes all strings provided via command line arguments
- We maintain the process.argv handling for Node.js command line input

**Output Requirements:**

- We still output the minimum distance found among all comparisons
- The output format matches the specification

**Array/String Access and Basic Looping:**

- The implementation still emphasizes array and string access
- We maintain the basic looping structure with nested for-loops
- String character comparisons are still done using direct array indexing

**Comment by Gkodkod** [comment]
For @Gkodkod
[Performance improvments to go code](https://github.com/bddicken/languages/pull/251/commits/0c2f6ff119e5c398327df9af25ee52ccd0b55339)
I've made several significant improvements to the Go implementation while maintaining strict compliance with the specification. Here are the key optimizations:

**Space Optimization:**

- Reduced space complexity from O(m*n) to O(min(m,n)) by using only two rows
- Always uses the shorter string as s1 to minimize memory usage
- Removed the unnecessary full matrix allocation

**Performance Optimizations:**

- Added early termination checks for common cases (identical strings, empty strings)
- Fixed the cost calculation (it was inverted in the original code)
- Removed the separate min function and inlined the comparison for better performance
- Cached string lengths to avoid repeated length calculations
- Used direct comparisons instead of function calls for finding minimum values

**Bug Fixes:**

- Fixed the cost calculation (original had 1 for match, 0 for mismatch which was incorrect)
- Fixed the comparison loop in main to match the specification (comparing each string with every other string)

**Code Quality Improvements:**

- Added comprehensive comments explaining the algorithm and optimizations
- Improved variable names for clarity
- Added proper error handling and exit codes
- Added detailed documentation about space and time complexity

**Specification Compliance:**

- Maintained exact output format ("times" and "min_distance")
- Kept the original comparison logic
- Preserved minDistance initialization to -1
- Maintained the Wagner-Fischer algorithm implementation

The code is now more efficient while still following the specification requirements about array/string access and basic looping constructs. The optimizations should provide better performance, especially for larger strings, while maintaining the exact same functionality and output format.

**Comment by PEZ** [comment]
This is of course @bddicken's call. But I can offer some thoughts.

It's super cool that there is so much to the Levenshtein algorithm. I'm super happy that @bddicken reminded me about it. It hade me check up Vladimir Levenshtein's Wikipedia. Wow, prolific dude. He contributed amazing stuff over many many decades! And I love reading your changes, @Gkodkod, and the rationale you sent along with them. I learned a lot!

However, I think there is a point with keeping the reference implementation naïve and simple. The benchmark is about the languages doing the same amount of the same type of work, afaiu. So if the reference implementations do something inefficient (like comparing distances twice as many times as needed) then that is fine and just means that we're benchmarking a bit more work (which is a good think in itself, because it makes the difference in start times smaller). And it should be easy to add a new language. To that end I think a small check script on the output could help, and it could help clarify that the extra work _should_ be done. (If it is decided that it should be done.)

There is a risk in that the project will promote the too naïve ways of solving problems. Like it is madness to do fibonacci series with recursion if you want to examine higher fib numbers. And the levenshtein algorithm obviously can be implemented with more rigor. I suggest, that if we end up staying with the first levenshtein idea, that we update the readmes and provide some examples of how it can be made more proper in real projects.

**Comment by Gkodkod** [comment]
@PEZ Thanks for the thoughtful feedback and it is certainly important not just to learn but to also apply our improved contributions!  

@bddicken Benjamin's input would be truly valuable as well.

As someone related to Vladimir Levenshtein (my name is Gal Levinshtein), this discussion is meaningful to me. Vladimir's pioneering work on the Levenshtein algorithm in 1965 laid the foundation for critical tools in fields like error correction, NLP, and computational biology. The Wagner-Fischer algorithm, as a dynamic programming approach, is perfect for benchmarks due to its clarity and focus on core operations like array indexing, looping, and conditionals.

I agree that keeping the reference implementation simple ensures consistent benchmarking across languages, even if it involves redundant computations. This approach highlights startup differences and ensures fair comparisons. However, naïve implementations can risk promoting inefficient coding practices. Production-ready optimizations, like rolling arrays or SIMD, could reduce memory and improve performance but may not align with the benchmark's goals.

I completely agree that keeping the reference implementation naïve and simple serves a clear purpose here. Benchmarking should measure the same type and amount of work across languages to ensure consistency. I can see how redundant computations, like comparing distances twice, might actually highlight start-up differences, which could be valuable for the benchmark's goals. Yet, I am not too certain that's the only approach.

In terms of our benchmark's performance evaluation, the spec is brilliantly focused. It ensures that all implementations compute the same type and amount of work using Wagner-Fischer, which highlights each language's ability to handle array and string manipulations. By keeping the reference implementations naïve, we avoid over-optimizing for specific languages and allow fair comparison of fundamental runtime characteristics, including startup time and raw execution speed.

That said, it's worth noting that overly simplistic implementations **can risk promoting inefficient coding practices**. For example, the recursive Fibonacci is a classic teaching example, but no one would use it for high-performance tasks. Similarly, while the Wagner-Fischer algorithm provides a baseline, production-ready versions might use rolling arrays to reduce memory usage or SIMD for speedups.

Additionally, aside from this PR's improvements, I also implemented the algorithm the same more efficient way adding 24 more languages.  https://github.com/bddicken/languages/pull/253

To address this balance, may I suggest the following:

1. **Documenting the goals and constraints:** A clear README should explain that the purpose of these implementations is benchmarking, not production efficiency.  Unless, we try to merge and test my improvements as well to see real performance.  All my code is documented and we can extract the docs to explain different efficiencies in more detail. 

2. **Providing educational insights**: Include notes or examples of how Levenshtein can be implemented more rigorously in real-world applications (like the ones I added to all the code,) showing optimizations like space and time reduction.

3. **Encouraging community learning**: The benchmark code I've added here and in the [24 languages PR](https://github.com/bddicken/languages/pull/253) can serve as a tool to inspire exploration of how the same algorithm performs under different constraints or optimizations.

4. **Maintaining Simplicity** -  I assure you that my changes still adhere to the benchmark's primary goals: simplicity, comparability, and accessibility. Also, adding these languages does not complicate the project but enhances its value.  Could we add testing for these changes and see how they improve our over whole benchmarking results ?

Lastly, as Benjamin mentioned in another PR, Mr. Vyacheslav Egorov, the Senior Staff Software and Compiler Engineer at [Google](https://www.linkedin.com/company/google/), wrote in [Microbenchmarks are experiments](https://mrale.ph/blog/2024/11/27/microbenchmarks-are-experiments.html), referring to this scientific experiment repo & emphasizes:

( • ) Control: Manage factors like CPU frequency.

( • ) Significance: Use statistics for reliable results.

( • ) Isolation: Test one variable at a time.

( • ) Interpretation: Watch for misleading small differences.

( • ) Reproducibility: Ensure consistent outcomes.

( • ) Application: Focus on impactful optimizations.

( • ) Misconceptions: Context matters in applying results.

Egorov pushes for a rigorous approach to benchmarking. It is a call to treat microbenchmarks with the seriousness and methodological rigor of scientific inquiry, ensuring that the pursuit of performance optimization is both accurate and meaningful.

I think this approach respects the benchmark's Benjamin's and Egorov's goals while providing educational value and honoring Vladimir Levenshtein's legacy as a problem-solver and thinker.  Additionally, it stays consistent and accessible, but we also educate developers on best practices as Egorov mentions in depth.  

What are your thoughts?

**Comment by PEZ** [comment]
Awesome. I wondered about your last name. 😀

**Comment by bddicken** [comment]
@Gkodkod Wow, thanks for all of this work and thoughtful analysis.

For one, quite interesting that you are related to Vladimir Levenshtein? If it's not too personal of a question, would you mind sharing more about how you are related? I'm curious!

This is a very interesting improvement. 

Really, I don't actually care too much about using the most efficient version of this (or the other) algorithms. The purpose of this benchmark is not to implement the *fastest* version of algorithms in some language, but to implement it the *same* way across languages, even if suboptimal, so that we can get a sense of the performance of things like looping, conditionals, memory allocation, etc across languages.

However, the sheer of effort you've put in here, and the amount of languages you are proposing adding, is quite impressive. I'm going to look at this tonight and if things look good I will likely get this merged in and update the levenshtein readme accordingly.

**Comment by bddicken** [comment]
OK, I'm gonna add this in, thank you again!

**Comment by Gkodkod** [comment]
Hi @bddicken Benjamin,

Thank you for your thoughtful comments and insights! I appreciate your perspective on the benchmarking process and the focus on consistency across implementations which I tried to achieve across all the languages, rather than solely on efficiency. It’s refreshing to see such a collaborative approach to exploring performance across different languages and I am also impressed by the exceptional work you display on your blog.

My late father and Dr. Vladimir Iosifovich Levenshtein were distant cousins by birth, both Jewish and sadly, it was before WW2's Holocaust and that's all I can share here publicly on a personal note.  

It is worth noting in relations to our discussion, that Dr. Levenshtein did research in information theory and error-correcting codes.  Among his other contributions, he is also known for the Levenshtein distance algorithm, which he developed in 1965. Dr. Levenshtein graduated from the Department of Mathematics and Mechanics of Moscow State University in 1958 and has worked at the Keldysh Institute of Applied Mathematics in Moscow ever since till he passed away 2017. He was a fellow of the IEEE Information Theory Society and a recipient of the 2006 Richard W. Hamming Medal (for “For contributions to the theory of error-correcting codes and information theory, including the Levenshtein distance”).  

Dr. Levenshtein has provided the best-known universal bounds to optimal sizes of codes and designs in metric spaces, including the Hamming space and the Euclidean sphere. In particular, they led to the discovery of the long-sought kissing numbers for n=8 and n=24.  Dr. Levenshtein authored optimal constructions for several error correcting problems, including: codes that correct a quarter or more of the errors present; codes with a given comma free index; perfect codes able to correct single deletions and single peak shifts; and binary codes with a given probability of undetected error. His work on the universal efficient coding of integers has led to algorithms that offer promising applications in data compression, like the Levenstein variable-length code.

I’m pleased to hear that you found the work impressive and have merged it for the benefit of others. I also want to commend you on your outstanding blog and the remarkable work you share in such a humble, clear, and concise manner. It’s an honor to correspond with you as we all share similar work, and I’m learning and re-learning a great deal from your tremendous insights, as well.  The AWS latency visualization is very useful for production usage.  I also just discovered your databases videos a few seconds ago seeing a moving face !  WOW 😃

May I ask, what software did you use to create the amazingly kewl moving graphics ?

**Pull request merged**
