### PR TITLE
Add critique section

### PR DESCRIPTION
**Pull request by diimdeep**
self explanatory

### CODE REVIEW

**Comment by PEZ** [comment]
I don't think we need this.

**Comment by diimdeep** [comment]
PR was made in a good faith, please elaborate in a good faith why exactly "we" as society do not need this.

**Comment by diimdeep** [comment]
@cmuratori
@ThePrimeagen

**Comment by cyrusmsk** [comment]
LGTM

**Comment by Citrus0299** [comment]
Yeah we don't need criticism let us keep wasting other peoples time

**Comment by ThePrimeagen** [comment]
This is most certainly not my intention. I am allowed to like or dislike whatever, but I do not approv, going into people's projects and asserting my opinion. 

This project can continue to thrive all it would like , and it does not bother me

**Pull request closed without merging**
