### PR TITLE
Enable JIT and disable XDebug for PHP

### PR DESCRIPTION
**Pull request by CViniciusSDias**
I enabled JIT and disabled XDebug on PHP to make the benchmark a bit more fair. A debugger can severely slow down the execution and other languages have JIT enabled.

### CODE REVIEW

**Review by Hattorius — APPROVED** [review]
Good job frien

**Comment by WhiteCranee** [comment]
The run.sh is written so you cd into the test you want to perform either you cd into loops or fibonacci and then execute the run.sh from there so it performs the commands relativ to your current directory.

**Comment by CViniciusSDias** [comment]
I missread the README.md, @WhiteCranee . I read `./run.sh` instead of `../run.sh`. Thank you. I removed it.

**Comment by bddicken** [comment]
Thanks for the contribution.

Jit was added in a separate PR, however.

**Pull request closed without merging**
